name: Simple CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a new directory
      run: mkdir -p my_new_directory

    - name: Write a message to a file
      run: echo "This is a message from GitHub Actions" > my_new_directory/message.txt

    - name: List directory contents
      run: ls -la my_new_directory

